name: Develop CI

on:
  push:
    branches: 
      - develop
  pull_request_target:
    types: 
      - closed
    branches: 
      - develop

jobs:

  develop-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Resolve dependencies
        run: make dependencies
        working-directory: ./server

      - name: Build
        run: make build
        working-directory: ./server

      - name: Test
        run: make test
        working-directory: ./server

      - name: Tag creation
        run: |
          TAG="build-$(date +'%d-%m-%Y_%H-%M-%S')"
          git tag $TAG
          git push origin $TAG
